// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request for
/// [CopyBackup][google.bigtable.admin.v2.BigtableTableAdmin.CopyBackup].
///
/// [google.bigtable.admin.v2.BigtableTableAdmin.CopyBackup]: <doc:BigtableTableAdmin/copyBackup(request:)>
public struct CopyBackupRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the destination cluster that will contain the backup
  /// copy. The cluster must already exist. Values are of the form:
  /// `projects/{project}/instances/{instance}/clusters/{cluster}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The id of the new backup. The `backup_id` along with `parent`
  /// are combined as {parent}/backups/{backup_id} to create the full backup
  /// name, of the form:
  /// `projects/{project}/instances/{instance}/clusters/{cluster}/backups/{backup_id}`.
  /// This string must be between 1 and 50 characters in length and match the
  /// regex [_a-zA-Z0-9][-_.a-zA-Z0-9]*.
  public var backupId: Swift.String = Swift.String()

  /// Required. The source backup to be copied from.
  /// The source backup needs to be in READY state for it to be copied.
  /// Copying a copied backup is not allowed.
  /// Once CopyBackup is in progress, the source backup cannot be deleted or
  /// cleaned up on expiration until CopyBackup is finished.
  /// Values are of the form:
  /// `projects/<project>/instances/<instance>/clusters/<cluster>/backups/<backup>`.
  public var sourceBackup: Swift.String = Swift.String()

  /// Required. Required. The expiration time of the copied backup with
  /// microsecond granularity that must be at least 6 hours and at most 30 days
  /// from the time the request is received. Once the `expire_time` has
  /// passed, Cloud Bigtable will delete the backup and free the resources used
  /// by the backup.
  public var expireTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `CopyBackupRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CopyBackupRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.CopyBackupRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
