// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// Encryption information for a given resource.
/// If this resource is protected with customer managed encryption, the in-use
/// Cloud Key Management Service (Cloud KMS) key version is specified along with
/// its status.
public struct EncryptionInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The type of encryption used to protect this resource.
  public var encryptionType: EncryptionInfo.EncryptionType = EncryptionInfo.EncryptionType()

  /// Output only. The status of encrypt/decrypt calls on underlying data for
  /// this resource. Regardless of status, the existing data is always encrypted
  /// at rest.
  public var encryptionStatus: GoogleRpc.Status? = nil

  /// Output only. The version of the Cloud KMS key specified in the parent
  /// cluster that is in use for the data underlying this table.
  public var kmsKeyVersion: Swift.String = Swift.String()

  /// Initialize a new instance of `EncryptionInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EncryptionInfo().with { $0.encryptionType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible encryption types for a resource.
  public enum EncryptionType: Codable, Equatable, Sendable {
    /// Encryption type was not specified, though data at rest remains encrypted.
    case unspecified
    /// The data backing this resource is encrypted at rest with a key that is
    /// fully managed by Google. No key version or status will be populated.
    /// This is the default state.
    case googleDefaultEncryption
    /// The data backing this resource is encrypted at rest with a key that is
    /// managed by the customer.
    /// The in-use version of the key and its status are populated for
    /// CMEK-protected tables.
    /// CMEK-protected backups are pinned to the key version that was in use at
    /// the time the backup was taken. This key version is populated but its
    /// status is not tracked and is reported as `UNKNOWN`.
    case customerManagedEncryption
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .googleDefaultEncryption: return 1
      case .customerManagedEncryption: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ENCRYPTION_TYPE_UNSPECIFIED"
      case .googleDefaultEncryption: return "GOOGLE_DEFAULT_ENCRYPTION"
      case .customerManagedEncryption: return "CUSTOMER_MANAGED_ENCRYPTION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EncryptionType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ENCRYPTION_TYPE_UNSPECIFIED": self = .unspecified
      case "GOOGLE_DEFAULT_ENCRYPTION": self = .googleDefaultEncryption
      case "CUSTOMER_MANAGED_ENCRYPTION": self = .customerManagedEncryption
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EncryptionType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .googleDefaultEncryption
      case 2: self = .customerManagedEncryption
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .googleDefaultEncryption: return try container.encode(1)
      case .customerManagedEncryption: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.EncryptionInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
