// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Information about a table restore.
public struct RestoreInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type of the restore source.
  public var sourceType: RestoreSourceType = RestoreSourceType()

  /// Information about the source used to restore the table.
  public var sourceInfo: OneOf_SourceInfo? = nil

  /// Initialize a new instance of `RestoreInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestoreInfo().with { $0.sourceType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case sourceType = "sourceType"
    case backupInfo = "backupInfo"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.sourceType = try container.decode(RestoreSourceType.self, forKey: .sourceType)

    var sourceInfo: OneOf_SourceInfo? = nil
    let sourceInfoCheckAndSet = {
      if sourceInfo != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'sourceInfo'"))
      }
      sourceInfo = $0
    }
    if let backupInfo = try container.decodeIfPresent(BackupInfo?.self, forKey: .backupInfo) {
      try sourceInfoCheckAndSet(.backupInfo(backupInfo))
    }
    self.sourceInfo = sourceInfo
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sourceType, forKey: .sourceType)

    if let choice = self.sourceInfo {
      switch choice {
      case .backupInfo(let value):
        try container.encode(value, forKey: .backupInfo)
      }
    }
  }

  /// Information about the source used to restore the table.
  public enum OneOf_SourceInfo: Codable, Equatable, Sendable {
    /// Information about the backup used to restore the table. The backup
    /// may no longer exist.
    indirect case backupInfo(BackupInfo?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.RestoreInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
