// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Rule to specify what data is stored in a storage tier.
public struct TieredStorageRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Rules to specify what data is stored in this tier.
  public var rule: OneOf_Rule? = nil

  /// Initialize a new instance of `TieredStorageRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TieredStorageRule().with { $0.includeIfOlderThan = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case includeIfOlderThan = "includeIfOlderThan"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var rule: OneOf_Rule? = nil
    let ruleCheckAndSet = {
      if rule != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'rule'"
          ))
      }
      rule = $0
    }
    if let includeIfOlderThan = try container.decodeIfPresent(
      GoogleCloudWkt.Duration?.self, forKey: .includeIfOlderThan)
    {
      try ruleCheckAndSet(.includeIfOlderThan(includeIfOlderThan))
    }
    self.rule = rule
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.rule {
      switch choice {
      case .includeIfOlderThan(let value):
        try container.encode(value, forKey: .includeIfOlderThan)
      }
    }
  }

  /// Rules to specify what data is stored in this tier.
  public enum OneOf_Rule: Codable, Equatable, Sendable {
    /// Include cells older than the given age.
    /// For the infrequent access tier, this value must be at least 30 days.
    indirect case includeIfOlderThan(GoogleCloudWkt.Duration?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.TieredStorageRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
