// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Information about a backup.
public struct BackupInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Name of the backup.
  public var backup: Swift.String = Swift.String()

  /// Output only. The time that the backup was started. Row data in the backup
  /// will be no older than this timestamp.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. This time that the backup was finished. Row data in the
  /// backup will be no newer than this timestamp.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Name of the table the backup was created from.
  public var sourceTable: Swift.String = Swift.String()

  /// Output only. Name of the backup from which this backup was copied. If a
  /// backup is not created by copying a backup, this field will be empty. Values
  /// are of the form:
  /// projects/<project>/instances/<instance>/clusters/<cluster>/backups/<backup>
  public var sourceBackup: Swift.String = Swift.String()

  /// Initialize a new instance of `BackupInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupInfo().with { $0.backup = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.BackupInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
