// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol BigtableInstanceAdminStub: Sendable {
    func createInstance(
      request: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getInstance(
      request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Instance

    func listInstances(
      request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListInstancesResponse

    func updateInstance(
      request: Instance, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Instance

    func partialUpdateInstance(
      request: PartialUpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createCluster(
      request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getCluster(
      request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Cluster

    func listClusters(
      request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListClustersResponse

    func updateCluster(
      request: Cluster, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func partialUpdateCluster(
      request: PartialUpdateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCluster(
      request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createAppProfile(
      request: CreateAppProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.AppProfile

    func getAppProfile(
      request: GetAppProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.AppProfile

    func listAppProfiles(
      request: ListAppProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListAppProfilesResponse

    func updateAppProfile(
      request: UpdateAppProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteAppProfile(
      request: DeleteAppProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listHotTablets(
      request: ListHotTabletsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListHotTabletsResponse

    func createLogicalView(
      request: CreateLogicalViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getLogicalView(
      request: GetLogicalViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.LogicalView

    func listLogicalViews(
      request: ListLogicalViewsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListLogicalViewsResponse

    func updateLogicalView(
      request: UpdateLogicalViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteLogicalView(
      request: DeleteLogicalViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createMaterializedView(
      request: CreateMaterializedViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getMaterializedView(
      request: GetMaterializedViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.MaterializedView

    func listMaterializedViews(
      request: ListMaterializedViewsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListMaterializedViewsResponse

    func updateMaterializedView(
      request: UpdateMaterializedViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteMaterializedView(
      request: DeleteMaterializedViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
