// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class BigtableTableAdminLogging: BigtableTableAdminStub {
    let inner: any BigtableTableAdminStub
    let logger: Logger

    public init(_ inner: any BigtableTableAdminStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-bigtable-admin-v2"
      logger[metadataKey: "gcp.client.service"] = "bigtableadmin"
      logger[metadataKey: "gcp.experimental.swift.client"] = "BigtableTableAdmin"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createTable(
      request: CreateTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Table {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTable",
        action: {
          (r: CreateTableRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.Table
          in
          return try await self.inner.createTable(request: r, options: o)
        })
    }

    public func createTableFromSnapshot(
      request: CreateTableFromSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTableFromSnapshot",
        action: {
          (r: CreateTableFromSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createTableFromSnapshot(request: r, options: o)
        })
    }

    public func listTables(
      request: ListTablesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListTablesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTables",
        action: {
          (r: ListTablesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListTablesResponse
          in
          return try await self.inner.listTables(request: r, options: o)
        })
    }

    public func getTable(
      request: GetTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Table {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTable",
        action: {
          (r: GetTableRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.Table
          in
          return try await self.inner.getTable(request: r, options: o)
        })
    }

    public func updateTable(
      request: UpdateTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTable",
        action: {
          (r: UpdateTableRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateTable(request: r, options: o)
        })
    }

    public func deleteTable(
      request: DeleteTableRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTable",
        action: { (r: DeleteTableRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTable(request: r, options: o)
        })
    }

    public func undeleteTable(
      request: UndeleteTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "undeleteTable",
        action: {
          (r: UndeleteTableRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.undeleteTable(request: r, options: o)
        })
    }

    public func createAuthorizedView(
      request: CreateAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAuthorizedView",
        action: {
          (r: CreateAuthorizedViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAuthorizedView(request: r, options: o)
        })
    }

    public func listAuthorizedViews(
      request: ListAuthorizedViewsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListAuthorizedViewsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAuthorizedViews",
        action: {
          (r: ListAuthorizedViewsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListAuthorizedViewsResponse
          in
          return try await self.inner.listAuthorizedViews(request: r, options: o)
        })
    }

    public func getAuthorizedView(
      request: GetAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.AuthorizedView {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAuthorizedView",
        action: {
          (r: GetAuthorizedViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.AuthorizedView
          in
          return try await self.inner.getAuthorizedView(request: r, options: o)
        })
    }

    public func updateAuthorizedView(
      request: UpdateAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateAuthorizedView",
        action: {
          (r: UpdateAuthorizedViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateAuthorizedView(request: r, options: o)
        })
    }

    public func deleteAuthorizedView(
      request: DeleteAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAuthorizedView",
        action: {
          (r: DeleteAuthorizedViewRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAuthorizedView(request: r, options: o)
        })
    }

    public func modifyColumnFamilies(
      request: ModifyColumnFamiliesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Table {
      try await self._intercept(
        request: request,
        options: options,
        name: "modifyColumnFamilies",
        action: {
          (r: ModifyColumnFamiliesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.Table
          in
          return try await self.inner.modifyColumnFamilies(request: r, options: o)
        })
    }

    public func dropRowRange(
      request: DropRowRangeRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "dropRowRange",
        action: { (r: DropRowRangeRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.dropRowRange(request: r, options: o)
        })
    }

    public func generateConsistencyToken(
      request: GenerateConsistencyTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.GenerateConsistencyTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateConsistencyToken",
        action: {
          (r: GenerateConsistencyTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.GenerateConsistencyTokenResponse
          in
          return try await self.inner.generateConsistencyToken(request: r, options: o)
        })
    }

    public func checkConsistency(
      request: CheckConsistencyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.CheckConsistencyResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "checkConsistency",
        action: {
          (r: CheckConsistencyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.CheckConsistencyResponse
          in
          return try await self.inner.checkConsistency(request: r, options: o)
        })
    }

    public func snapshotTable(
      request: SnapshotTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "snapshotTable",
        action: {
          (r: SnapshotTableRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.snapshotTable(request: r, options: o)
        })
    }

    public func getSnapshot(
      request: GetSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Snapshot {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSnapshot",
        action: {
          (r: GetSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.Snapshot
          in
          return try await self.inner.getSnapshot(request: r, options: o)
        })
    }

    public func listSnapshots(
      request: ListSnapshotsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListSnapshotsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSnapshots",
        action: {
          (r: ListSnapshotsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListSnapshotsResponse
          in
          return try await self.inner.listSnapshots(request: r, options: o)
        })
    }

    public func deleteSnapshot(
      request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSnapshot",
        action: { (r: DeleteSnapshotRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSnapshot(request: r, options: o)
        })
    }

    public func createBackup(
      request: CreateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBackup",
        action: {
          (r: CreateBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackup(request: r, options: o)
        })
    }

    public func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Backup {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackup",
        action: {
          (r: GetBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.Backup
          in
          return try await self.inner.getBackup(request: r, options: o)
        })
    }

    public func updateBackup(
      request: UpdateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Backup {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBackup",
        action: {
          (r: UpdateBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.Backup
          in
          return try await self.inner.updateBackup(request: r, options: o)
        })
    }

    public func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBackup",
        action: { (r: DeleteBackupRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteBackup(request: r, options: o)
        })
    }

    public func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListBackupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBackups",
        action: {
          (r: ListBackupsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListBackupsResponse
          in
          return try await self.inner.listBackups(request: r, options: o)
        })
    }

    public func restoreTable(
      request: RestoreTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "restoreTable",
        action: {
          (r: RestoreTableRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.restoreTable(request: r, options: o)
        })
    }

    public func copyBackup(
      request: CopyBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "copyBackup",
        action: {
          (r: CopyBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.copyBackup(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func createSchemaBundle(
      request: CreateSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSchemaBundle",
        action: {
          (r: CreateSchemaBundleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createSchemaBundle(request: r, options: o)
        })
    }

    public func updateSchemaBundle(
      request: UpdateSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSchemaBundle",
        action: {
          (r: UpdateSchemaBundleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateSchemaBundle(request: r, options: o)
        })
    }

    public func getSchemaBundle(
      request: GetSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.SchemaBundle {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSchemaBundle",
        action: {
          (r: GetSchemaBundleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.SchemaBundle
          in
          return try await self.inner.getSchemaBundle(request: r, options: o)
        })
    }

    public func listSchemaBundles(
      request: ListSchemaBundlesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListSchemaBundlesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSchemaBundles",
        action: {
          (r: ListSchemaBundlesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListSchemaBundlesResponse
          in
          return try await self.inner.listSchemaBundles(request: r, options: o)
        })
    }

    public func deleteSchemaBundle(
      request: DeleteSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSchemaBundle",
        action: {
          (r: DeleteSchemaBundleRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSchemaBundle(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
