// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol BigtableTableAdminStub: Sendable {
    func createTable(
      request: CreateTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Table

    func createTableFromSnapshot(
      request: CreateTableFromSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listTables(
      request: ListTablesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListTablesResponse

    func getTable(
      request: GetTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Table

    func updateTable(
      request: UpdateTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteTable(
      request: DeleteTableRequest, options: GoogleGax.RequestOptions
    ) async throws

    func undeleteTable(
      request: UndeleteTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createAuthorizedView(
      request: CreateAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listAuthorizedViews(
      request: ListAuthorizedViewsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListAuthorizedViewsResponse

    func getAuthorizedView(
      request: GetAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.AuthorizedView

    func updateAuthorizedView(
      request: UpdateAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteAuthorizedView(
      request: DeleteAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws

    func modifyColumnFamilies(
      request: ModifyColumnFamiliesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Table

    func dropRowRange(
      request: DropRowRangeRequest, options: GoogleGax.RequestOptions
    ) async throws

    func generateConsistencyToken(
      request: GenerateConsistencyTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.GenerateConsistencyTokenResponse

    func checkConsistency(
      request: CheckConsistencyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.CheckConsistencyResponse

    func snapshotTable(
      request: SnapshotTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getSnapshot(
      request: GetSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Snapshot

    func listSnapshots(
      request: ListSnapshotsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListSnapshotsResponse

    func deleteSnapshot(
      request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws

    func createBackup(
      request: CreateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Backup

    func updateBackup(
      request: UpdateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Backup

    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListBackupsResponse

    func restoreTable(
      request: RestoreTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func copyBackup(
      request: CopyBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func createSchemaBundle(
      request: CreateSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateSchemaBundle(
      request: UpdateSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getSchemaBundle(
      request: GetSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.SchemaBundle

    func listSchemaBundles(
      request: ListSchemaBundlesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListSchemaBundlesResponse

    func deleteSchemaBundle(
      request: DeleteSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
