// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [google.bigtable.admin.v2.BigtableTableAdmin.CheckConsistency][google.bigtable.admin.v2.BigtableTableAdmin.CheckConsistency]
///
/// [google.bigtable.admin.v2.BigtableTableAdmin.CheckConsistency]: <doc:BigtableTableAdminClient/checkConsistency(request:)>
public struct CheckConsistencyRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The unique name of the Table for which to check replication
  /// consistency. Values are of the form
  /// `projects/{project}/instances/{instance}/tables/{table}`.
  public var name: Swift.String = Swift.String()

  /// Required. The token created using GenerateConsistencyToken for the Table.
  public var consistencyToken: Swift.String = Swift.String()

  /// Which type of read needs to consistently observe which type of write?
  /// Default: `standard_read_remote_writes`
  public var mode: OneOf_Mode? = nil

  /// Initialize a new instance of `CheckConsistencyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CheckConsistencyRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case consistencyToken = "consistencyToken"
    case standardReadRemoteWrites = "standardReadRemoteWrites"
    case dataBoostReadLocalWrites = "dataBoostReadLocalWrites"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.consistencyToken = try container.decode(Swift.String.self, forKey: .consistencyToken)

    var mode: OneOf_Mode? = nil
    let modeCheckAndSet = {
      if mode != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'mode'"
          ))
      }
      mode = $0
    }
    if let standardReadRemoteWrites = try container.decodeIfPresent(
      StandardReadRemoteWrites?.self, forKey: .standardReadRemoteWrites)
    {
      try modeCheckAndSet(.standardReadRemoteWrites(standardReadRemoteWrites))
    }
    if let dataBoostReadLocalWrites = try container.decodeIfPresent(
      DataBoostReadLocalWrites?.self, forKey: .dataBoostReadLocalWrites)
    {
      try modeCheckAndSet(.dataBoostReadLocalWrites(dataBoostReadLocalWrites))
    }
    self.mode = mode
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.consistencyToken, forKey: .consistencyToken)

    if let choice = self.mode {
      switch choice {
      case .standardReadRemoteWrites(let value):
        try container.encode(value, forKey: .standardReadRemoteWrites)
      case .dataBoostReadLocalWrites(let value):
        try container.encode(value, forKey: .dataBoostReadLocalWrites)
      }
    }
  }

  /// Which type of read needs to consistently observe which type of write?
  /// Default: `standard_read_remote_writes`
  public enum OneOf_Mode: Codable, Equatable, Sendable {
    /// Checks that reads using an app profile with `StandardIsolation` can
    /// see all writes committed before the token was created, even if the
    /// read and write target different clusters.
    indirect case standardReadRemoteWrites(StandardReadRemoteWrites?)
    /// Checks that reads using an app profile with `DataBoostIsolationReadOnly`
    /// can see all writes committed before the token was created, but only if
    /// the read and write target the same cluster.
    indirect case dataBoostReadLocalWrites(DataBoostReadLocalWrites?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.CheckConsistencyRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
