// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A set of columns within a table which share a common configuration.
public struct ColumnFamily: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Garbage collection rule specified as a protobuf.
  /// Must serialize to at most 500 bytes.
  ///
  /// NOTE: Garbage collection executes opportunistically in the background, and
  /// so it's possible for reads to return a cell even if it matches the active
  /// GC expression for its family.
  public var gcRule: GcRule? = nil

  /// The type of data stored in each of this family's cell values, including its
  /// full encoding. If omitted, the family only serves raw untyped bytes.
  ///
  /// For now, only the `Aggregate` type is supported.
  ///
  /// `Aggregate` can only be set at family creation and is immutable afterwards.
  ///
  ///
  /// If `value_type` is `Aggregate`, written data must be compatible with:
  ///  * `value_type.input_type` for `AddInput` mutations
  public var valueType: Type_? = nil

  /// Initialize a new instance of `ColumnFamily`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ColumnFamily().with { $0.gcRule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.ColumnFamily"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
