// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [google.bigtable.admin.v2.BigtableTableAdmin.CreateTable][google.bigtable.admin.v2.BigtableTableAdmin.CreateTable]
///
/// [google.bigtable.admin.v2.BigtableTableAdmin.CreateTable]: <doc:BigtableTableAdminClient/createTable(request:options:)>
public struct CreateTableRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The unique name of the instance in which to create the table.
  /// Values are of the form `projects/{project}/instances/{instance}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The name by which the new table should be referred to within the
  /// parent instance, e.g., `foobar` rather than `{parent}/tables/foobar`.
  /// Maximum 50 characters.
  public var tableId: Swift.String = Swift.String()

  /// Required. The Table to create.
  public var table: Table? = nil

  /// The optional list of row keys that will be used to initially split the
  /// table into several tablets (tablets are similar to HBase regions).
  /// Given two split keys, `s1` and `s2`, three tablets will be created,
  /// spanning the key ranges: `[, s1), [s1, s2), [s2, )`.
  ///
  /// Example:
  ///
  /// * Row keys := `["a", "apple", "custom", "customer_1", "customer_2",`
  ///                `"other", "zz"]`
  /// * initial_split_keys := `["apple", "customer_1", "customer_2", "other"]`
  /// * Key assignment:
  ///     - Tablet 1 `[, apple)                => {"a"}.`
  ///     - Tablet 2 `[apple, customer_1)      => {"apple", "custom"}.`
  ///     - Tablet 3 `[customer_1, customer_2) => {"customer_1"}.`
  ///     - Tablet 4 `[customer_2, other)      => {"customer_2"}.`
  ///     - Tablet 5 `[other, )                => {"other", "zz"}.`
  public var initialSplits: [CreateTableRequest.Split] = []

  /// Initialize a new instance of `CreateTableRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateTableRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// An initial split point for a newly created table.
  public struct Split: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Row key to use as an initial tablet boundary.
    public var key: Foundation.Data = Foundation.Data()

    /// Initialize a new instance of `Split`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Split().with { $0.key = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.bigtable.admin.v2.CreateTableRequest.Split"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.CreateTableRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
