// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for
/// [google.bigtable.admin.v2.BigtableTableAdmin.DropRowRange][google.bigtable.admin.v2.BigtableTableAdmin.DropRowRange]
///
/// [google.bigtable.admin.v2.BigtableTableAdmin.DropRowRange]: <doc:BigtableTableAdminClient/dropRowRange(request:options:)>
public struct DropRowRangeRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The unique name of the table on which to drop a range of rows.
  /// Values are of the form
  /// `projects/{project}/instances/{instance}/tables/{table}`.
  public var name: Swift.String = Swift.String()

  /// Delete all rows or by prefix.
  public var target: OneOf_Target? = nil

  /// Initialize a new instance of `DropRowRangeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DropRowRangeRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case rowKeyPrefix = "rowKeyPrefix"
    case deleteAllDataFromTable = "deleteAllDataFromTable"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)

    var target: OneOf_Target? = nil
    let targetCheckAndSet = {
      if target != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'target'"))
      }
      target = $0
    }
    if let rowKeyPrefix = try container.decodeIfPresent(Foundation.Data.self, forKey: .rowKeyPrefix)
    {
      try targetCheckAndSet(.rowKeyPrefix(rowKeyPrefix))
    }
    if let deleteAllDataFromTable = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .deleteAllDataFromTable)
    {
      try targetCheckAndSet(.deleteAllDataFromTable(deleteAllDataFromTable))
    }
    self.target = target
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.target {
      switch choice {
      case .rowKeyPrefix(let value):
        try container.encode(value, forKey: .rowKeyPrefix)
      case .deleteAllDataFromTable(let value):
        try container.encode(value, forKey: .deleteAllDataFromTable)
      }
    }
  }

  /// Delete all rows or by prefix.
  public enum OneOf_Target: Codable, Equatable, Sendable {
    /// Delete all rows that start with this row key prefix. Prefix cannot be
    /// zero length.
    case rowKeyPrefix(Foundation.Data)
    /// Delete all rows in the table. Setting this to false is a no-op.
    case deleteAllDataFromTable(Swift.Bool)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.DropRowRangeRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
