// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A tablet is a defined by a start and end key and is explained in
/// https://cloud.google.com/bigtable/docs/overview#architecture and
/// https://cloud.google.com/bigtable/docs/performance#optimization.
/// A Hot tablet is a tablet that exhibits high average cpu usage during the time
/// interval from start time to end time.
public struct HotTablet: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The unique name of the hot tablet. Values are of the form
  /// `projects/{project}/instances/{instance}/clusters/{cluster}/hotTablets/[a-zA-Z0-9_-]*`.
  public var name: Swift.String = Swift.String()

  /// Name of the table that contains the tablet. Values are of the form
  /// `projects/{project}/instances/{instance}/tables/[_a-zA-Z0-9][-_.a-zA-Z0-9]*`.
  public var tableName: Swift.String = Swift.String()

  /// Output only. The start time of the hot tablet.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The end time of the hot tablet.
  public var endTime: GoogleCloudWKT.Timestamp? = nil

  /// Tablet Start Key (inclusive).
  public var startKey: Swift.String = Swift.String()

  /// Tablet End Key (inclusive).
  public var endKey: Swift.String = Swift.String()

  /// Output only. The average CPU usage spent by a node on this tablet over the
  /// start_time to end_time time range. The percentage is the amount of CPU used
  /// by the node to serve the tablet, from 0% (tablet was not interacted with)
  /// to 100% (the node spent all cycles serving the hot tablet).
  public var nodeCpuUsagePercent: Swift.Float = Swift.Float()

  /// Initialize a new instance of `HotTablet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HotTablet().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.HotTablet"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
