// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for BigtableInstanceAdmin.ListHotTablets.
public struct ListHotTabletsResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// List of hot tablets in the tables of the requested cluster that fall
  /// within the requested time range. Hot tablets are ordered by node cpu usage
  /// percent. If there are multiple hot tablets that correspond to the same
  /// tablet within a 15-minute interval, only the hot tablet with the highest
  /// node cpu usage will be included in the response.
  public var hotTablets: [HotTablet] = []

  /// Set if not all hot tablets could be returned in a single response.
  /// Pass this value to `page_token` in another request to get the next
  /// page of results.
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListHotTabletsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListHotTabletsResponse().with { $0.hotTablets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.ListHotTabletsResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [HotTablet] {
    return self.hotTablets
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
