// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for BigtableInstanceAdmin.ListHotTablets.
public struct ListHotTabletsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The cluster name to list hot tablets.
  /// Value is in the following form:
  /// `projects/{project}/instances/{instance}/clusters/{cluster}`.
  public var parent: Swift.String = Swift.String()

  /// The start time to list hot tablets. The hot tablets in the response will
  /// have start times between the requested start time and end time. Start time
  /// defaults to Now if it is unset, and end time defaults to Now - 24 hours if
  /// it is unset. The start time should be less than the end time, and the
  /// maximum allowed time range between start time and end time is 48 hours.
  /// Start time and end time should have values between Now and Now - 14 days.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// The end time to list hot tablets.
  public var endTime: GoogleCloudWKT.Timestamp? = nil

  /// Maximum number of results per page.
  ///
  /// A page_size that is empty or zero lets the server choose the number of
  /// items to return. A page_size which is strictly positive will return at most
  /// that many items. A negative page_size will cause an error.
  ///
  /// Following the first request, subsequent paginated calls do not need a
  /// page_size field. If a page_size is set in subsequent calls, it must match
  /// the page_size given in the first request.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The value of `next_page_token` returned by a previous call.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListHotTabletsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListHotTabletsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.ListHotTabletsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
