// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [google.bigtable.admin.v2.BigtableTableAdmin.ModifyColumnFamilies][google.bigtable.admin.v2.BigtableTableAdmin.ModifyColumnFamilies]
///
/// [google.bigtable.admin.v2.BigtableTableAdmin.ModifyColumnFamilies]: <doc:BigtableTableAdminClient/modifyColumnFamilies(request:)>
public struct ModifyColumnFamiliesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The unique name of the table whose families should be modified.
  /// Values are of the form
  /// `projects/{project}/instances/{instance}/tables/{table}`.
  public var name: Swift.String = Swift.String()

  /// Required. Modifications to be atomically applied to the specified table's
  /// families. Entries are applied in order, meaning that earlier modifications
  /// can be masked by later ones (in the case of repeated updates to the same
  /// family, for example).
  public var modifications: [ModifyColumnFamiliesRequest.Modification] = []

  /// Optional. If true, ignore safety checks when modifying the column families.
  public var ignoreWarnings: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ModifyColumnFamiliesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ModifyColumnFamiliesRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A create, update, or delete of a particular column family.
  public struct Modification: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The ID of the column family to be modified.
    public var id: Swift.String = Swift.String()

    /// Optional. A mask specifying which fields (e.g. `gc_rule`) in the `update`
    /// mod should be updated, ignored for other modification types. If unset or
    /// empty, we treat it as updating `gc_rule` to be backward compatible.
    public var updateMask: GoogleCloudWkt.FieldMask? = nil

    /// Column family modifications.
    public var mod: OneOf_Mod? = nil

    /// Initialize a new instance of `Modification`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Modification().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case id = "id"
      case create = "create"
      case update = "update"
      case drop = "drop"
      case updateMask = "updateMask"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.id = try container.decode(Swift.String.self, forKey: .id)
      self.updateMask = try container.decodeIfPresent(
        GoogleCloudWkt.FieldMask.self, forKey: .updateMask)

      var mod: OneOf_Mod? = nil
      let modCheckAndSet = {
        if mod != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'mod'"))
        }
        mod = $0
      }
      if let create = try container.decodeIfPresent(ColumnFamily?.self, forKey: .create) {
        try modCheckAndSet(.create(create))
      }
      if let update = try container.decodeIfPresent(ColumnFamily?.self, forKey: .update) {
        try modCheckAndSet(.update(update))
      }
      if let drop = try container.decodeIfPresent(Swift.Bool.self, forKey: .drop) {
        try modCheckAndSet(.drop(drop))
      }
      self.mod = mod
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.id, forKey: .id)
      try container.encode(self.updateMask, forKey: .updateMask)

      if let choice = self.mod {
        switch choice {
        case .create(let value):
          try container.encode(value, forKey: .create)
        case .update(let value):
          try container.encode(value, forKey: .update)
        case .drop(let value):
          try container.encode(value, forKey: .drop)
        }
      }
    }

    /// Column family modifications.
    public enum OneOf_Mod: Codable, Equatable, Sendable {
      /// Create a new column family with the specified schema, or fail if
      /// one already exists with the given ID.
      indirect case create(ColumnFamily?)
      /// Update an existing column family to the specified schema, or fail
      /// if no column family exists with the given ID.
      indirect case update(ColumnFamily?)
      /// Drop (delete) the column family with the given ID, or fail if no such
      /// family exists.
      case drop(Swift.Bool)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.bigtable.admin.v2.ModifyColumnFamiliesRequest.Modification"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.ModifyColumnFamiliesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
