// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents a protobuf schema.
public struct ProtoSchema: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Contains a protobuf-serialized
  /// [google.protobuf.FileDescriptorSet](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/descriptor.proto),
  /// which could include multiple proto files.
  /// To generate it, [install](https://grpc.io/docs/protoc-installation/) and
  /// run `protoc` with
  /// `--include_imports` and `--descriptor_set_out`. For example, to generate
  /// for moon/shot/app.proto, run
  /// ```
  /// $protoc  --proto_path=/app_path --proto_path=/lib_path \
  ///          --include_imports \
  ///          --descriptor_set_out=descriptors.pb \
  ///          moon/shot/app.proto
  /// ```
  /// For more details, see protobuffer [self
  /// description](https://developers.google.com/protocol-buffers/docs/techniques#self-description).
  public var protoDescriptors: Foundation.Data = Foundation.Data()

  /// Initialize a new instance of `ProtoSchema`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProtoSchema().with { $0.protoDescriptors = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.ProtoSchema"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
