// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request for
/// [RestoreTable][google.bigtable.admin.v2.BigtableTableAdmin.RestoreTable].
///
/// [google.bigtable.admin.v2.BigtableTableAdmin.RestoreTable]: <doc:BigtableTableAdminClient/restoreTable(request:)>
public struct RestoreTableRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the instance in which to create the restored
  /// table. Values are of the form `projects/<project>/instances/<instance>`.
  public var parent: Swift.String = Swift.String()

  /// Required. The id of the table to create and restore to. This
  /// table must not already exist. The `table_id` appended to
  /// `parent` forms the full table name of the form
  /// `projects/<project>/instances/<instance>/tables/<table_id>`.
  public var tableId: Swift.String = Swift.String()

  /// Required. The source from which to restore.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `RestoreTableRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestoreTableRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case parent = "parent"
    case tableId = "tableId"
    case backup = "backup"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.tableId = try container.decode(Swift.String.self, forKey: .tableId)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let backup = try container.decodeIfPresent(Swift.String.self, forKey: .backup) {
      try sourceCheckAndSet(.backup(backup))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.tableId, forKey: .tableId)

    if let choice = self.source {
      switch choice {
      case .backup(let value):
        try container.encode(value, forKey: .backup)
      }
    }
  }

  /// Required. The source from which to restore.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Name of the backup from which to restore.  Values are of the form
    /// `projects/<project>/instances/<instance>/clusters/<cluster>/backups/<backup>`.
    case backup(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.RestoreTableRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
