// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A named collection of related schemas.
public struct SchemaBundle: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The unique name identifying this schema bundle.
  /// Values are of the form
  /// `projects/{project}/instances/{instance}/tables/{table}/schemaBundles/{schema_bundle}`
  public var name: Swift.String = Swift.String()

  /// Optional. The etag for this schema bundle.
  /// This may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding. The server
  /// returns an ABORTED error on a mismatched etag.
  public var etag: Swift.String = Swift.String()

  /// The type of this schema bundle. The oneof case cannot change after
  /// creation.
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `SchemaBundle`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SchemaBundle().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case protoSchema = "protoSchema"
    case etag = "etag"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.etag = try container.decode(Swift.String.self, forKey: .etag)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let protoSchema = try container.decodeIfPresent(ProtoSchema?.self, forKey: .protoSchema) {
      try typeCheckAndSet(.protoSchema(protoSchema))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.etag, forKey: .etag)

    if let choice = self.type {
      switch choice {
      case .protoSchema(let value):
        try container.encode(value, forKey: .protoSchema)
      }
    }
  }

  /// The type of this schema bundle. The oneof case cannot change after
  /// creation.
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// Schema for Protobufs.
    indirect case protoSchema(ProtoSchema?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.SchemaBundle"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
