// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for
/// [google.bigtable.admin.v2.BigtableTableAdmin.SnapshotTable][google.bigtable.admin.v2.BigtableTableAdmin.SnapshotTable]
///
/// Note: This is a private alpha release of Cloud Bigtable snapshots. This
/// feature is not currently available to most Cloud Bigtable customers. This
/// feature might be changed in backward-incompatible ways and is not recommended
/// for production use. It is not subject to any SLA or deprecation policy.
///
/// [google.bigtable.admin.v2.BigtableTableAdmin.SnapshotTable]: <doc:BigtableTableAdminClient/snapshotTable(request:options:)>
public struct SnapshotTableRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The unique name of the table to have the snapshot taken.
  /// Values are of the form
  /// `projects/{project}/instances/{instance}/tables/{table}`.
  public var name: Swift.String = Swift.String()

  /// Required. The name of the cluster where the snapshot will be created in.
  /// Values are of the form
  /// `projects/{project}/instances/{instance}/clusters/{cluster}`.
  public var cluster: Swift.String = Swift.String()

  /// Required. The ID by which the new snapshot should be referred to within the
  /// parent cluster, e.g., `mysnapshot` of the form:
  /// `[_a-zA-Z0-9][-_.a-zA-Z0-9]*` rather than
  /// `projects/{project}/instances/{instance}/clusters/{cluster}/snapshots/mysnapshot`.
  public var snapshotId: Swift.String = Swift.String()

  /// The amount of time that the new snapshot can stay active after it is
  /// created. Once 'ttl' expires, the snapshot will get deleted. The maximum
  /// amount of time a snapshot can stay active is 7 days. If 'ttl' is not
  /// specified, the default value of 24 hours will be used.
  public var ttl: GoogleCloudWkt.Duration? = nil

  /// Description of the snapshot.
  public var description: Swift.String = Swift.String()

  /// Initialize a new instance of `SnapshotTableRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SnapshotTableRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.SnapshotTableRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
