// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request for
/// [UpdateSchemaBundle][google.bigtable.admin.v2.BigtableTableAdmin.UpdateSchemaBundle].
///
/// [google.bigtable.admin.v2.BigtableTableAdmin.UpdateSchemaBundle]: <doc:BigtableTableAdminClient/updateSchemaBundle(request:options:)>
public struct UpdateSchemaBundleRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The schema bundle to update.
  ///
  /// The schema bundle's `name` field is used to identify the schema bundle to
  /// update. Values are of the form
  /// `projects/{project}/instances/{instance}/tables/{table}/schemaBundles/{schema_bundle}`
  public var schemaBundle: SchemaBundle? = nil

  /// Optional. The list of fields to update.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Optional. If set, ignore the safety checks when updating the Schema Bundle.
  /// The safety checks are:
  /// - The new Schema Bundle is backwards compatible with the existing Schema
  /// Bundle.
  public var ignoreWarnings: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `UpdateSchemaBundleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateSchemaBundleRequest().with { $0.schemaBundle = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.UpdateSchemaBundleRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
