// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request for
/// [UpdateTable][google.bigtable.admin.v2.BigtableTableAdmin.UpdateTable].
///
/// [google.bigtable.admin.v2.BigtableTableAdmin.UpdateTable]: <doc:BigtableTableAdminClient/updateTable(request:options:)>
public struct UpdateTableRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The table to update.
  /// The table's `name` field is used to identify the table to update.
  public var table: Table? = nil

  /// Required. The list of fields to update.
  /// A mask specifying which fields (e.g. `change_stream_config`) in the `table`
  /// field should be updated. This mask is relative to the `table` field, not to
  /// the request message. The wildcard (*) path is currently not supported.
  /// Currently UpdateTable is only supported for the following fields:
  ///
  /// * `change_stream_config`
  /// * `change_stream_config.retention_period`
  /// * `deletion_protection`
  /// * `row_key_schema`
  ///
  /// If `column_families` is set in `update_mask`, it will return an
  /// UNIMPLEMENTED error.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Optional. If true, ignore safety checks when updating the table.
  public var ignoreWarnings: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `UpdateTableRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateTableRequest().with { $0.table = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.UpdateTableRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
