// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request for
/// [UpdateAuthorizedView][google.bigtable.admin.v2.BigtableTableAdmin.UpdateAuthorizedView].
///
/// [google.bigtable.admin.v2.BigtableTableAdmin.UpdateAuthorizedView]: <doc:BigtableTableAdminClient/updateAuthorizedView(request:)>
public struct UpdateAuthorizedViewRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The AuthorizedView to update. The `name` in `authorized_view` is
  /// used to identify the AuthorizedView. AuthorizedView name must in this
  /// format:
  /// `projects/{project}/instances/{instance}/tables/{table}/authorizedViews/{authorized_view}`.
  public var authorizedView: AuthorizedView? = nil

  /// Optional. The list of fields to update.
  /// A mask specifying which fields in the AuthorizedView resource should be
  /// updated. This mask is relative to the AuthorizedView resource, not to the
  /// request message. A field will be overwritten if it is in the mask. If
  /// empty, all fields set in the request will be overwritten. A special value
  /// `*` means to overwrite all fields (including fields not set in the
  /// request).
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Optional. If true, ignore the safety checks when updating the
  /// AuthorizedView.
  public var ignoreWarnings: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `UpdateAuthorizedViewRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateAuthorizedViewRequest().with { $0.authorizedView = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.UpdateAuthorizedViewRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
